name: Publish Package to npmjs

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Manually set .npmrc
        run: |
          # The token works fine in my own .npmjs, but for some reason the .npmrc that is being set up
          # is not being picked up, manually setting the first line didnt work, maybe its the second?
          # we might need 
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./cratedb_sqlparse_js/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Generate grammar
        run: |
          python -m pip install -r requirements.txt
          python setup_grammar.py javascript

      - name: Set VERSION from tag
        working-directory: 'cratedb_sqlparse_js'
        run: |
          npm version ${GITHUB_REF#refs/*/v}

      - name: Build package
        working-directory: 'cratedb_sqlparse_js'
        run: npm install && npm run build

      - run: npm publish --provenance --access public --registry=https://registry.npmjs.org/:authToken=${{ secrets.NPM_TOKEN }}
        working-directory: 'cratedb_sqlparse_js'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
